#!/bin/sh

THIS_FOLDER_NAME=$(dirname $0)

if [ -z $1 ]; then
	$THIS_FOLDER_NAME/commands/--ls $THIS_FOLDER_NAME $@
	exit
fi

for COMMAND in $(ls $THIS_FOLDER_NAME/commands)
do
  if [ "$1"x == "$COMMAND"x ]; then
    shift
    $THIS_FOLDER_NAME/commands/$COMMAND $THIS_FOLDER_NAME $@
    exit
  fi
done

echo invalid command: $1
echo usage: "$0 command (params, ...)" where command is one of: $(ls $THIS_FOLDER_NAME/commands)
exit
